version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
    - "9411:9411"
  service-a:
    image: sleuth_service_a
    build:
      context: .
      dockerfile: sleuth-service-a/Dockerfile
    environment:
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1.0
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      ZUUL_ROUTES_TEST_URL: http://service-b:8080
    ports:
    - 8080
    depends_on:
    - zipkin
  service-b:
    image: sleuth_service_b
    build:
      context: .
      dockerfile: sleuth-service-b/Dockerfile
    environment:
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1.0
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
    ports:
    - 8080
    depends_on:
    - zipkin
  # web:
  #   build:
  #     context: sleuth-js